### ISSUE TITLE
Some questions about the method

### ISSUE THREAD

**Issue by Buffyqsf** [Lab-of-AI-and-Robotics/GS_ICP_SLAM#11]
Thanks four your great work! I got some questions about the method you proposed. 
First, you treat keyframe and mapping-only frame seperately. If only tracking on keyframes, I want to know how do you get the pose of mapping-only frames?
Second, I don't understand the scale regularization in your paper very well, can you point out the related code? 
Thank you very much!

**Comment by Riboha** [comment]
Thanks for your interest in our work!

In our system, we estimate the camera pose on every frame. Keyframes are the subset of frames that are considered to contain essential Gaussians for tracking, and we add Gaussians in the keyframes to the 3DGS map. 

Scale regularization is implemented in our submodule, fast_gicp. Please refer to calculating source covariances, and setting target covariances parts in fast_gicp.
