### ISSUE TITLE
Question about training strategy.

### ISSUE THREAD

**Issue by Buffyqsf** [Lab-of-AI-and-Robotics/GS_ICP_SLAM#16]
Thanks for your great work. I tried to read your source code, but I'm not sure how you train your Gaussian model. 
In the mapping process, after the initialization is complete, it enters a True loop until the end of the process. 
That is to say, the training of Gaussian model is iterative as much as possible in the whole process without other constraints?

**Comment by Riboha** [comment]
In our system, the whole system is divided into two processes, mapping and tracking process.
The tracking process loads the dataset, and if the tracking process arrives at the end of the dataset, it terminates all processes.

As you can see in the mapper process code, the following line to the while True.

while True:
            if self.end_of_dataset[0]:
                break

**Comment by Buffyqsf** [comment]
Yeah, I saw this. So the mapping process keeps running throughout the whole reconstruction process. 
I later read your source code and found that there are some shared flag that control the running of each process. Amazing work thanks for sharing.
