### ISSUE TITLE
About the installization of rerun

### ISSUE THREAD

**Issue by kk6398** [Lab-of-AI-and-Robotics/GS_ICP_SLAM#19]
Hi, I try to intall rerun by "pip install rerun", but it occurs the bug that 
"ERROR: Could not find a version that satisfies the requirement rerun-sdk (from versions: none)
ERROR: No matching distribution found for rerun-sdk"

what method to solve it?
![image](https://github.com/Lab-of-AI-and-Robotics/GS_ICP_SLAM/assets/70420660/afd81b30-c1a8-40a2-ae06-cc619270bc1c)

**Comment by Riboha** [comment]
Hello,

To install rerun.io, you need to type "pip install rerun-sdk". Is it working now?

**Comment by kk6398** [comment]
Yep, I think it need to use this code"pip install rerun-sdk", but it doesnot work, the bug displats as the picture above.

**Comment by AtticusZeller** [comment]
+1

**Comment by Riboha** [comment]
Maybe this will be helpful for you!

# https://github.com/rerun-io/rerun/issues/1320#issuecomment-1431900098
