### ISSUE TITLE
The problem of reduced frame continuity

### ISSUE THREAD

**Issue by Tokyo-dream** [Lab-of-AI-and-Robotics/GS_ICP_SLAM#29]
Thanks again for the excellent work
However, through the experiment, the images in the Replica room0 data set are selected 1 frame every 5 frames to get 400 pictures, and GS-ICP is run, but the effect is not ideal. Would you like to ask whether this is the limitation of the method or what parameters can be adjusted to solve it. Compared to SplaTAM, the effect is normal
SplaTAM
<img width="1261" alt="屏幕截图 2024-05-17 122348" src="https://github.com/Lab-of-AI-and-Robotics/GS_ICP_SLAM/assets/63401220/15792492-baf2-48e7-bdc2-e13920901d62">
GS-ICP-SLAM
![download](https://github.com/Lab-of-AI-and-Robotics/GS_ICP_SLAM/assets/63401220/d28bbc8d-c4ca-45d3-9f84-00873d2a1b27)

**Comment by Riboha** [comment]
Hello!
In the original replica dataset, the movement of the camera between frames is small, and the default parameters of GS-ICP-SLAM are fitted to this environment. 
Could you try adjusting the max_correspondence_distance parameter to be a bit larger?
(ex: 0.1)
