### ISSUE TITLE
environment version

### ISSUE THREAD

**Issue by 9796l** [Lab-of-AI-and-Robotics/GS_ICP_SLAM#30]
Hello, i am very grateful for your excellent work. When i want to set environment, submodule gs_gicp need PCL. I git pcl from github, but errors:
CMake Error at pcl_gpu_octree_generated_bfrs.cu.o.None.cmake:282 (message):
  Error generating file
/home/lt/SLAM/GS_ICP_SLAM/pcl/release/gpu/octree/CMakeFiles/pcl_gpu_octree.dir/src/cuda/./pcl_gpu_octree_generated_bfrs.cu.o
gpu/octree/CMakeFiles/pcl_gpu_octree.dir/build.make:1151: recipe for target 'gpu/octree/CMakeFiles/pcl_gpu_octree.dir/src/cuda/pcl_gpu_octree_generated_bfrs.cu.o' failed
make[2]: *** [gpu/octree/CMakeFiles/pcl_gpu_octree.dir/src/cuda/pcl_gpu_octree_generated_bfrs.cu.o] Error 1
CMakeFiles/Makefile2:5538: recipe for target 'gpu/octree/CMakeFiles/pcl_gpu_octree.dir/all' failed
make[1]: *** [gpu/octree/CMakeFiles/pcl_gpu_octree.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2

i want to know the ubuntu version. i know cuda==11.8,but what is the vision of ubuntu?mybe this is the reason of the errors. i am very grateful for your reply!

**Comment by Riboha** [comment]
Hello, sorry for the late response. I tested GS-ICP SLAM on ubuntu 20.04!
