### ISSUE TITLE
Can the demo run without using traj.txt

### ISSUE THREAD

**Issue by songhc8** [Lab-of-AI-and-Robotics/GS_ICP_SLAM#41]
Thanks for sharing your incredible work. 

I collect dataset using my own rgb-d camera. But I can not obtain the camera pose i.e.I do not have the file "traj.txt" 

I wonder if I orgnized my data as what Replica did, and update my camera_info.txt. Is it possible to run the demo whithout traj.txt file?

thanks.

**Comment by Lucasmogsan** [comment]
@songhc8 did you find a solution to this?

**Comment by songhc8** [comment]
> @songhc8 did you find a solution to this?

nope...

**Comment by songhc8** [comment]
> @songhc8 did you find a solution to this?

nope

**Comment by Zlzxzw1234** [comment]
I also want to run this demo on my own data,can we talk with each other more?
