### ISSUE TITLE
Nothing in /results after running

### ISSUE THREAD

**Issue by JinXJinLeX** [Lab-of-AI-and-Robotics/GS_ICP_SLAM#6]
There is nothing in ../experiments/results/ after I run tum.sh, is it the only way to visualize by SIBR_viewer? How can I get a traj or .ply file?

**Comment by LemonSoda-RPG** [comment]
I encountered the same issue while running it with Docker.
There is nothing in experiments/results

**Comment by youzi260** [comment]
I also encountered the same problem. There is nothing under the result. Have you solved this problem?

**Comment by Riboha** [comment]
Exporting results are not implemented, but I'm working on it!
It will be added soon.

**Comment by JinXJinLeX** [comment]
> Exporting results are not implemented, but I'm working on it! It will be added soon.

Looking forward to it! Thanks for your excellent work!

**Comment by KwanWaiPang** [comment]
> There is nothing in ../experiments/results/ after I run tum.sh, is it the only way to visualize by SIBR_viewer? How can I get a traj or .ply file?

hi~do you successfully use the SIBR_viewer to visualize the result? I can not get any result after I run the ./install/bin/SIBR_remoteGaussian_app --rendering-size 1280 720

![微信截图_20240411154748](https://github.com/Lab-of-AI-and-Robotics/GS_ICP_SLAM/assets/44108932/195a4ed8-2009-4e82-9c9c-87bd1b7ae0d0)

**Comment by ian-pge** [comment]
Hi, did you launch the slam algorithm before the visualization tool ?
