### ISSUE TITLE
PCL dependency 

### ISSUE THREAD

**Issue by HowoongJun** [Lab-of-AI-and-Robotics/GS_ICP_SLAM#7]
Hello, 

I think this repository has PCL dependency due to Fast-GICP submodule

Please note this on README file. 

Thank you

**Comment by Riboha** [comment]
Thanks for your suggestion! I added a brief comment to the README.md.
(I also added the Dockerfile!)

**Comment by HowoongJun** [comment]
Thank you ! 
MAybe, writing PCL version on README file would be helpful for others :)
