### ISSUE TITLE
Error with "FT_Done_MM_Var", tested in Ubuntu18.04

### ISSUE THREAD

**Issue by shuttworth** [Lab-of-AI-and-Robotics/GS_ICP_SLAM#9]
[ 88%] Linking CXX executable devel/lib/fast_gicp/gicp_kitti
/home/wangshouan/anaconda3/lib/libfontconfig.so.1: undefined reference to `FT_Done_MM_Var'
collect2: error: ld returned 1 exit status
CMakeFiles/gicp_kitti.dir/build.make:430: recipe for target 'devel/lib/fast_gicp/gicp_kitti' failed
make[2]: *** [devel/lib/fast_gicp/gicp_kitti] Error 1
CMakeFiles/Makefile2:350: recipe for target 'CMakeFiles/gicp_kitti.dir/all' failed
make[1]: *** [CMakeFiles/gicp_kitti.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable devel/lib/fast_gicp/gicp_align
[100%] Built target gicp_align
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kk6398** [comment]
> [ 88%] Linking CXX executable devel/lib/fast_gicp/gicp_kitti /home/wangshouan/anaconda3/lib/libfontconfig.so.1: undefined reference to `FT_Done_MM_Var' collect2: error: ld returned 1 exit status CMakeFiles/gicp_kitti.dir/build.make:430: recipe for target 'devel/lib/fast_gicp/gicp_kitti' failed make[2]: *** [devel/lib/fast_gicp/gicp_kitti] Error 1 CMakeFiles/Makefile2:350: recipe for target 'CMakeFiles/gicp_kitti.dir/all' failed make[1]: *** [CMakeFiles/gicp_kitti.dir/all] Error 2 make[1]: *** Waiting for unfinished jobs.... [100%] Linking CXX executable devel/lib/fast_gicp/gicp_align [100%] Built target gicp_align Makefile:145: recipe for target 'all' failed make: *** [all] Error 2

I met the same issue with you. Do you have any methods to solve it?

**Comment by scpoppin1207** [comment]
Me too have this problem.
